# Generated by Django 5.1 on 2024-08-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "backendapp",
            "0002_log_team_subscription_credit_teammember_team_members_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="pending_invitations",
            new_name="pending_emails",
        ),
    ]
