# Generated by Django 5.1 on 2024-08-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendapp", "0003_rename_pending_invitations_team_pending_emails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="pending_emails",
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.CharField(
                blank=True, help_text="Comma-separated emails", max_length=500
            ),
        ),
    ]
