# Generated by Django 5.1 on 2024-08-25 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendapp", "0004_remove_team_pending_emails_remove_team_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="pending_emails",
            field=models.CharField(
                blank=True, help_text="Comma-separated emails", max_length=500
            ),
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                through="backendapp.TeamMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
