# Generated by Django 5.1 on 2024-08-25 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendapp", "0007_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="AItools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="credit",
            name="total_credits",
            field=models.IntegerField(default=200),
        ),
    ]
