# Generated by Django 4.2.15 on 2024-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendapp", "0008_aitool_user_alter_credit_total_credits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
