import "@/assets/css/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#0a0118] scroll-smooth">{children}</body>
    </html>
  );
}
